(ns solana-clj.sysvar
  (:require
    ["@solana/web3.js" :as sol]))

(def ^:const SYSVAR_CLOCK_PUBKEY sol/SYSVAR_CLOCK_PUBKEY)
(def ^:const SYSVAR_RECENT_BLOCKHASHES_PUBKEY sol/SYSVAR_RECENT_BLOCKHASHES_PUBKEY)
(def ^:const SYSVAR_RENT_PUBKEY sol/SYSVAR_RENT_PUBKEY)
(def ^:const SYSVAR_REWARDS_PUBKEY sol/SYSVAR_REWARDS_PUBKEY)
(def ^:const SYSVAR_STAKE_HISTORY_PUBKEY sol/SYSVAR_STAKE_HISTORY_PUBKEY)
(def ^:const SYSVAR_INSTRUCTIONS_PUBKEY sol/SYSVAR_INSTRUCTIONS_PUBKEY)
